# Generated by Django 5.1.1 on 2025-03-03 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='text',
        ),
    ]
